apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeployment
  labels:
    app: my_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my_app
  template:
    metadata:
      labels:
        app: my_app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
